version: '3.4'

services:
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: ServiceInvocation/Booking.Api/Dockerfile
  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: ServiceInvocation/Stock.Api/Dockerfile
